// Textes structurés des 18 planches d'observation du Bestiaire.
// Source de vérité : Sensetho_Concept_Marque/build_bestiaire_planches.cjs
// (régénéré via scratchpad/extract_planches.cjs — ne pas éditer à la main).

export interface Planche {
  mode: string; meca: string; traduction: string; forces: string; vigilances: string; adequation: string
}

export const PLANCHES: Record<string, Planche> = {
  manchot: {
    mode: 'La cohésion par l\'adversité',
    meca: 'Par −60 °C, des milliers de manchots se serrent en une masse compacte : ~37 °C au centre, le vent en périphérie. Aucun chef, aucun lien d\'affinité — ce qui les rassemble, c\'est le froid. Et la position exposée tourne entre tous, par ondes lentes.',
    traduction: 'Une équipe soudée par l\'épreuve, non par l\'affinité ni la hiérarchie. On n\'a pas besoin de s\'aimer pour survivre ensemble : la cohésion naît de la menace partagée, et la place la plus dure tourne entre tous.',
    forces: 'Résilience extrême sous pression · solidarité sans chef · aucun bouc émissaire laissé seul dans le froid · tient des conditions que nul ne tiendrait isolé.',
    vigilances: 'La cohésion tient tant que dure l\'adversité : le beau temps revenu, la masse se disperse. Elle survit mais ne conquiert pas — confondre soudure de crise et projet commun.',
    adequation: 'À l\'aise : cellules de crise, retournements, marchés rudes, « hivers » saisonniers. En souffrance : croissance calme exigeant vision, initiative et affinité — la colonie attend que l\'hiver passe, elle ne part pas à la chasse.',
  },
  cheval: {
    mode: 'Le leadership distribué et la vigilance partagée',
    meca: 'L\'étalon protège et fait face, mais ne décide pas de la direction : le mouvement est initié par une jument expérimentée — ou par n\'importe qui, selon les liens sociaux. Chaque individu apporte un talent sensoriel ; la peur d\'un seul se propage à tous.',
    traduction: 'Une organisation où le chef visible n\'est pas le décideur réel : la direction émerge de l\'expérience ou de celui qui sent le danger le premier. Chacun est reconnu pour un talent propre — et l\'ambiance est une information.',
    forces: 'Leadership souple et contextuel · vigilance collective · réactivité au danger · reconnaissance des talents · continuité protégée par les « anciennes ».',
    vigilances: 'La panique se propage aussi vite que l\'information · un chef visible qui se croit décideur alors qu\'il n\'est que protecteur · les changements brutaux de tête effacent l\'héritage.',
    adequation: 'À l\'aise : environnements incertains exigeant vigilance et adaptation, cultures valorisant les talents distribués. En souffrance : contextes exigeant une chaîne de décision unique et rapide — le distribué hésite, la sensibilité vire à l\'instabilité.',
  },
  lion: {
    mode: 'La division du travail par la visibilité — et la succession par conquête',
    meca: 'Le mâle visible défend le territoire et prend les coups ; les lionnes, discrètes, assurent l\'essentiel de la chasse coordonnée. À la succession, le nouveau venu s\'impose par la force — et efface l\'héritage du précédent.',
    traduction: 'Une organisation où la figure de proue occupe la lumière pendant que la production réelle est assurée par des équipes discrètes — et où les successions se jouent en conquête, chaque nouveau dirigeant défaisant ce que l\'ancien a bâti.',
    forces: 'Spécialisation efficace · production collective discrète et coordonnée · défense claire du territoire · courage de la figure de proue.',
    vigilances: 'L\'invisibilité des « lionnes » démotive ceux qui produisent · la succession par conquête détruit la valeur accumulée · dépendance à la figure visible.',
    adequation: 'À l\'aise : marchés à défendre âprement, où produire et protéger sont deux métiers distincts. En souffrance : cultures de continuité et de reconnaissance partagée.',
  },
  fourmi: {
    mode: 'La coordination sans chef (stigmergie)',
    meca: 'Des millions d\'individus, aucun donneur d\'ordres : la reine pond, elle ne commande pas. La coordination passe par les traces laissées dans le milieu — phéromones, pistes, signaux — que chacun lit et renforce.',
    traduction: 'Une organisation qui se coordonne par les process, les outils partagés, les données et les tableaux de bord plutôt que par la réunion et l\'ordre hiérarchique. Chacun sait quoi faire en lisant le système, pas en attendant le chef.',
    forces: 'Robustesse (aucun point de défaillance unique) · optimisation collective · passage à l\'échelle massif · pas besoin de superviser.',
    vigilances: 'Rigidité des castes · perte de sens individuel — nul n\'existe hors de sa fonction · on suit la piste même quand elle mène au mauvais endroit.',
    adequation: 'À l\'aise : grands volumes, process répétables, environnements stables. En souffrance : contextes exigeant initiative individuelle, créativité de rupture, décision rapide hors-piste.',
  },
  abeille: {
    mode: 'La décision collective démocratique',
    meca: 'Pour choisir un nouveau nid, des éclaireuses prospectent et reviennent danser pour « plaider » leur site ; les autres vont vérifier par elles-mêmes. La décision se prend par quorum : le meilleur choix gagne par recrutement, personne ne tranche seul.',
    traduction: 'Une organisation qui décide par exploration distribuée, débat et quorum : on envoie des éclaireurs, chacun défend sa trouvaille, on vérifie, et l\'option qui convainc le plus de monde l\'emporte. Les rôles évoluent avec l\'expérience.',
    forces: 'Décisions de grande qualité · adhésion (chacun a participé) · exploration large avant de trancher · transmission par paliers d\'expérience.',
    vigilances: 'Lenteur si le quorum tarde · suppose une vraie culture du débat honnête · vulnérable si les « danses » deviennent de la communication plutôt que de l\'information vérifiée.',
    adequation: 'À l\'aise : choix stratégiques importants et peu réversibles, cultures matures. En souffrance : urgence vitale exigeant une décision immédiate.',
  },
  loup: {
    mode: 'La meute-famille (au-delà du mythe de l\'alpha)',
    meca: 'Le « mâle alpha » dominateur est un mythe né de loups captifs, désavoué par son propre auteur : une meute sauvage est une famille — les parents guident, nourrissent, coordonnent la chasse. La coopération permet d\'abattre bien plus gros que soi.',
    traduction: 'Une organisation où l\'autorité légitime ressemble à une parentalité : protéger, transmettre, coordonner — non écraser. Le vrai « alpha » n\'est pas le plus brutal : c\'est celui qui prend soin du groupe.',
    forces: 'Loyauté · rôles clairs · capacité à « chasser » plus gros que soi · transmission intergénérationnelle.',
    vigilances: 'Esprit de clan, fermeture à l\'extérieur · confusion entre autorité et domination — le mythe alpha qui légitime la brutalité managériale.',
    adequation: 'À l\'aise : équipes soudées poursuivant un objectif ambitieux commun. En souffrance : besoin d\'ouverture, de diversité, de coopération inter-équipes — le clan se referme.',
  },
  etourneau: {
    mode: 'L\'alignement sans commandement',
    meca: 'Des dizaines de milliers d\'oiseaux ondulent comme un seul corps — sans aucun chef. Chacun n\'ajuste sa trajectoire qu\'à ses ~7 voisins les plus proches ; de ces règles locales émerge un alignement global instantané.',
    traduction: 'Une organisation agile et alignée non par le contrôle central, mais par quelques règles partagées et l\'attention aux plus proches. L\'information circule de proche en proche ; l\'alignement global naît de la cohérence locale.',
    forces: 'Agilité extrême · résilience (pas de tête à abattre) · alignement sans bureaucratie · réaction collective ultra-rapide.',
    vigilances: 'Pas de cap intentionnel — la nuée tournoie, elle ne décide pas d\'une destination · mimétisme aveugle · suppose des règles partagées claires et une vraie proximité.',
    adequation: 'À l\'aise : organisations distribuées, agiles, à forte autonomie locale. En souffrance : projets exigeant une direction explicite et tenue dans la durée.',
  },
  castor: {
    mode: 'L\'ingénieur d\'écosystème',
    meca: 'Espèce clé : en construisant des barrages, le castor transforme un ruisseau en zone humide dont dépendent quantité d\'autres espèces. Il ne s\'adapte pas à son milieu — il le façonne durablement, au prix d\'un entretien permanent.',
    traduction: 'Ceux qui transforment l\'environnement commun au bénéfice de tous : bâtisseurs d\'infrastructures, de plateformes, d\'outils, de cadres. Leur valeur n\'est pas dans la production directe mais dans le milieu qu\'ils rendent possible.',
    forces: 'Ténacité · effet de levier (un seul ouvrage profite à tout l\'écosystème) · vision long terme · rôle structurant.',
    vigilances: 'Sur-ingénierie (« usine à gaz ») · rigidité des ouvrages · inonder l\'amont — transformer le milieu au détriment de certains · entretien sans fin.',
    adequation: 'À l\'aise : phases de construction, scale-up, fondations communes. En souffrance : contextes exigeant légèreté et réversibilité, environnements déjà saturés de structures.',
  },
  elephant: {
    mode: 'Le matriarcat de la mémoire',
    meca: 'La harde suit la matriarche, la femelle la plus âgée : elle sait où trouver l\'eau lors des sécheresses extrêmes, reconnaît les menaces, garde la carte sociale du groupe. Les petits sont élevés collectivement.',
    traduction: 'Une organisation où l\'autorité vient du savoir accumulé et de l\'expérience, non de la force ni du titre. La mémoire institutionnelle est l\'actif vital — et le soin des nouveaux, une affaire collective.',
    forces: 'Sagesse · stabilité · gestion des crises (« on a déjà connu pire ») · transmission · solidarité intergénérationnelle.',
    vigilances: 'Dépendance à une personne-mémoire — risque majeur à son départ · conservatisme · lenteur au changement de paradigme.',
    adequation: 'À l\'aise : environnements à crises récurrentes où l\'expérience sauve, cultures de transmission. En souffrance : ruptures technologiques où l\'expérience passée devient un piège.',
  },
  suricate: {
    mode: 'La sentinelle à tour de rôle',
    meca: 'Pendant que le groupe cherche sa nourriture, un individu monte la garde et lance un cri d\'alarme calibré selon le prédateur. Le rôle tourne — souvent pris par un individu déjà rassasié : un altruisme coordonné et soutenable.',
    traduction: 'Une organisation où quelqu\'un veille pendant que les autres produisent, et où ce rôle de vigie tourne équitablement. On travaille la tête baissée parce qu\'on sait qu\'un autre regarde l\'horizon.',
    forces: 'Détection précoce des menaces · confiance et relais · partage équitable d\'un rôle ingrat · alertes calibrées, la bonne alerte au bon niveau.',
    vigilances: 'Fausses alertes, cris au loup · épuisement si le tour ne tourne pas vraiment · dépendance à l\'honnêteté du signal.',
    adequation: 'À l\'aise : environnements à risques fréquents exigeant veille et réactivité (sécurité, conformité, qualité, cyber). En souffrance : environnements stables où la vigilance permanente devient anxiété stérile.',
  },
  vampire: {
    mode: 'La réciprocité et la mémoire des dettes',
    meca: 'Deux nuits sans se nourrir et la chauve-souris vampire meurt ; les nuits de chasse sont aléatoires. Celles qui ont réussi partagent avec celles qui ont échoué — mais en priorité avec celles qui ont déjà donné : les resquilleuses sont exclues du réseau.',
    traduction: 'Une organisation tenue par un réseau de réciprocité : entraide, renvois d\'ascenseur, mémoire sociale de qui a aidé qui. Le capital social est une monnaie ; les passagers clandestins sont détectés et marginalisés.',
    forces: 'Résilience face à l\'aléa (mutualisation du risque) · forte cohésion par la dette d\'honneur · auto-régulation contre les profiteurs.',
    vigilances: 'Comptabilité implicite des dettes qui peut virer au clientélisme · exclusion brutale des « non-donneurs » · suppose des relations durables et une mémoire fiable.',
    adequation: 'À l\'aise : métiers à aléa fort où l\'entraide sauve, petites communautés stables. En souffrance : organisations très transactionnelles ou à fort turnover — la réciprocité n\'a pas le temps de s\'établir.',
  },
  nettoyeur: {
    mode: 'La relation de service et la réputation',
    meca: 'Le labre tient une « station de nettoyage » où de gros poissons viennent se faire débarrasser de leurs parasites. Il est tenté de tricher (mordre le mucus, plus nourrissant) — mais les clients observent comment il traite les autres : sa réputation le précède.',
    traduction: 'La relation de service : la valeur naît de l\'échange équilibré, mais la tentation de rogner sur la qualité est constante. Ce qui régule, c\'est la réputation observable — les clients se parlent. La confiance est un actif qui se voit.',
    forces: 'Création de valeur mutuelle · fidélisation par la réputation · régulation par le marché des regards.',
    vigilances: 'Tentation de tricher quand personne ne regarde · « effet vitrine » — bien servir seulement sous observation · réputation longue à bâtir, vite détruite.',
    adequation: 'À l\'aise : relations clients-fournisseurs durables, métiers de service, écosystèmes de partenaires. En souffrance : marchés anonymes, one-shot, sans mémoire — rien ne dissuade la triche.',
  },
  coucou: {
    mode: 'Le parasitisme de couvée (le passager clandestin)',
    meca: 'Le coucou pond dans le nid d\'une autre espèce ; son poussin éjecte les œufs de l\'hôte et monopolise les soins grâce à des signaux exagérés. S\'ensuit une course aux armements : l\'hôte apprend à reconnaître l\'intrus, le coucou perfectionne l\'imitation.',
    traduction: 'Le mode-ombre du bestiaire, à détecter : faire porter son effort par les autres, capter les ressources d\'un collectif sans contribuer, évincer les projets légitimes. Le pendant positif : la vigilance de l\'hôte, qui sait repérer et rejeter.',
    forces: '(Du point de vue du système hôte) La pression du parasite aiguise la vigilance et les défenses collectives — reconnaissance, contrôle.',
    vigilances: 'Captation de ressources · éviction des initiatives saines · épuisement des « hôtes » de bonne foi · défiance généralisée si la chasse au coucou devient paranoïaque.',
    adequation: 'Aucun milieu de prédilection à cultiver : utile uniquement comme grille de détection — « avons-nous des coucous, et savons-nous les reconnaître ? »',
  },
  poule: {
    mode: 'La hiérarchie de dominance',
    meca: 'Chaque poule sait qui elle peut picorer et qui la picore : une hiérarchie linéaire stable s\'établit — et, paradoxalement, les conflits cessent. Mais chaque nouvel arrivant relance les picotages, et le bas de l\'échelle subit.',
    traduction: 'Une organisation à statuts hiérarchiques marqués, explicites ou tacites. La clarté du rang apaise — chacun connaît sa place — mais fige les positions, écrase le bas, et rend chaque réorganisation violente.',
    forces: 'Clarté des statuts · prévisibilité · baisse des conflits ouverts une fois l\'ordre établi.',
    vigilances: 'Immobilité sociale · souffre-douleur en bas de l\'échelle · violence à chaque arrivée ou réorganisation · l\'innovation venue du bas est étouffée.',
    adequation: 'À l\'aise : environnements stables où la clarté du rang sécurise. En souffrance : besoin de mobilité, de méritocratie, d\'initiative venue du bas.',
  },
  banc: {
    mode: 'La dilution du risque par le nombre',
    meca: 'Des milliers de poissons bougent comme un seul corps. La protection vient du nombre : probabilité d\'être « le » poisson mangé qui chute, effet de confusion pour le prédateur, multiplicité des yeux. Aucun meneur : chacun s\'aligne sur ses voisins.',
    traduction: 'La sécurité par la masse : l\'individu réduit son risque personnel en se fondant dans le groupe — on ne dépasse pas, on suit le mouvement. Difficile, pour une menace externe, de cibler quelqu\'un en particulier.',
    forces: 'Protection collective · détection à plusieurs · réduction du risque individuel · cohésion de mouvement.',
    vigilances: 'Invisibilité de l\'individu · conformisme · dilution de la responsabilité — « quelqu\'un d\'autre s\'en occupera » · nul ne se distingue.',
    adequation: 'À l\'aise : environnements menaçants où se fondre protège (forte pression externe). En souffrance : besoin de responsabilité individuelle, de leadership visible, de différenciation.',
  },
  gnou: {
    mode: 'Le mouvement de masse et le suivisme',
    meca: 'Près d\'1,5 million de gnous migrent en boucle continue, sentant pluies et pâturages à distance. La force est l\'élan collectif — mais les traversées de rivières sont meurtrières : la masse pousse, et des individus sont sacrifiés au passage.',
    traduction: 'Une organisation en transformation permanente, portée par l\'élan. La masse franchit des obstacles que nul ne franchirait seul — mais le suivisme peut entraîner tout le monde vers le précipice, et les transitions font des victimes.',
    forces: 'Élan collectif · capacité à franchir l\'obstacle par la masse · flair collectif de la ressource — sentir « la pluie », le marché.',
    vigilances: 'Suivisme aveugle · bousculades et paniques · individus sacrifiés aux transitions · on suit même vers le mauvais gué.',
    adequation: 'À l\'aise : phases de transformation de masse, marchés en mouvement rapide. En souffrance : besoin de pause, de réflexion individuelle, de remise en cause du cap.',
  },
  pieuvre: {
    mode: 'L\'intelligence distribuée',
    meca: '~500 millions de neurones, dont les deux tiers dans les bras : chaque bras goûte, touche et réagit localement sans attendre l\'ordre central. Le cerveau fixe l\'intention ; les bras trouvent l\'exécution — avec, en prime, la maîtrise du camouflage.',
    traduction: 'Une intelligence fortement décentralisée : le centre donne le cap et l\'intention, des unités autonomes résolvent localement. Grande agilité, grande adaptation — mais l\'ensemble peut paraître illisible de l\'extérieur.',
    forces: 'Autonomie locale forte · agilité · résolution de problèmes · adaptation (camouflage).',
    vigilances: 'Illisibilité — que fait chaque bras ? · coordination difficile · le centre peut perdre le fil · peu de coopération entre unités.',
    adequation: 'À l\'aise : environnements complexes exigeant autonomie et adaptation rapide, organisations en réseau. En souffrance : besoin de cohérence visible, de standardisation, de coordination étroite.',
  },
  tortue: {
    mode: 'Le repli protecteur',
    meca: 'Face à la menace, la tortue ne fuit ni ne combat : elle se rétracte dans sa carapace. Défense passive qui échange la vitesse contre une protection blindée — et une longévité exceptionnelle. Elle survit par l\'endurance, non par la confrontation.',
    traduction: 'Les organisations qui répondent à la menace en se repliant dans leur coquille : protéger le cœur, ralentir, se fermer. Résilientes et durables — mais lentes, et la protection peut virer à l\'isolement.',
    forces: 'Résilience · longévité · protection du cœur · encaisse sans paniquer.',
    vigilances: 'Lenteur · fermeture, repli · perte de contact avec l\'extérieur · immobilisme — se protéger au lieu d\'agir.',
    adequation: 'À l\'aise : tempêtes à traverser, périodes où protéger le cœur prime, secteurs à temps long. En souffrance : besoin de vitesse, d\'ouverture, de conquête.',
  },
}
